name: Run bot

on:
  schedule:
    - cron: "0 7 * * *"   # 10:00 МСК
    - cron: "0 11 * * *"  # 14:00 МСК
    - cron: "0 16 * * *"  # 22:00 МСК
  workflow_dispatch:       # возможность запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false   # 🚫 запрещаем git push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          TG_CHANNEL: ${{ secrets.TG_CHANNEL }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_TOKEN: ${{ secrets.YT_TOKEN }}
        run: python bot.py
