name: Upload Anime Edits

on:
  schedule:
    - cron: "0 5 * * *"   # 10:00
    - cron: "0 9 * * *"   # 14:00
    - cron: "0 15 * * *"   # 22:00
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Restore YouTube token
        run: echo '${{ secrets.YT_TOKEN }}' > token.json

      - name: Run bot
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
          TG_CHANNEL: ${{ secrets.TG_CHANNEL }}
        run: python bot.py

      - name: Save counter
        uses: EndBug/add-and-commit@v9
        with:
          add: 'counter.json'
          message: 'update counter'
